apiVersion: v1
kind: ConfigMap
metadata:
  name: judge0-config
data:
  judge0.conf: |
    ################################################################################
    # Judge0 Configuration File
    ################################################################################
    # Default: true
    JUDGE0_TELEMETRY_ENABLE=false

    # Enable or disable (use 1 or 0) debug mode
    JUDGE0_DEBUG=1

    # Workers
    JUDGE0_WORKERS=3

    # Specify maximum queue size. Represents maximum number of submissions that
    # can wait in the queue at once. If request for new submission comes and the
    # queue if full then submission will be rejected.
    # Default: 100
    MAX_QUEUE_SIZE=300

    # PostgreSQL connection info
    POSTGRES_HOST=postgres
    POSTGRES_PORT=5432
    POSTGRES_DB=judge0
    POSTGRES_USER=judge0
    # POSTGRES_PASSWORD should be set as a Kubernetes secret

    # Redis connection info
    REDIS_HOST=redis
    REDIS_PORT=6379
    # REDIS_PASSWORD should be set as a Kubernetes secret
    
    # If true submission will by default be able to do network calls.
    # Default: false, i.e. programs cannot do network calls.
    ENABLE_NETWORK=true

    # Default runtime limit for every program (in seconds). Decimal numbers are allowed.
    # Time in which the OS assigns the processor to different tasks is not counted.
    # Default: 5
    CPU_TIME_LIMIT=8

    # Other Judge0 specific configurations...
    # Add all other necessary configurations from the original judge0.conf file
