---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: judge0
            - name: POSTGRES_USER
              value: judge0
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: judge0-secrets
                  key: postgres-password
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:6.0
          ports:
            - containerPort: 6379
          args: ["--requirepass", "$(REDIS_PASSWORD)"]
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: judge0-secrets
                  key: redis-password
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: judge0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: judge0
  template:
    metadata:
      labels:
        app: judge0
    spec:
      containers:
        - name: judge0
          image: judge0/judge0:latest
          imagePullPolicy: Always
          securityContext:
            privileged: true
          ports:
            - containerPort: 2358
          envFrom:
            - configMapRef:
                name: judge0-config
          env:
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: judge0
            - name: POSTGRES_USER
              value: judge0
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: judge0-secrets
                  key: postgres-password
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: judge0-secrets
                  key: redis-password
            - name: CPU_TIME_LIMIT
              value: "12"
            - name: WALL_TIME_LIMIT
              value: "16"
            - name: ENABLE_NETWORK
              value: "true"
          livenessProbe:
            httpGet:
              path: /config_info
              port: 2358
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /system_info
              port: 2358
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: judge0
spec:
  selector:
    app: judge0
  ports:
    - protocol: TCP
      port: 80
      targetPort: 2358
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: judge0-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: judge0
  minReplicas: 6
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
